# Generated by Django 4.2.8 on 2025-02-23 18:12

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utilities.fields.decimal


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان به روزرسانی')),
                ('balance', utilities.fields.decimal.CurrencyDecimalField(decimal_places=7, default=Decimal('0'), max_digits=22)),
                ('freeze', utilities.fields.decimal.CurrencyDecimalField(decimal_places=7, default=Decimal('0'), max_digits=22)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('user', 'currency'), name='wallet_unique_user_currency'),
        ),
    ]
