# Generated by Django 4.2.8 on 2025-02-23 18:12

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utilities.fields.decimal


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان به روزرسانی')),
                ('name', models.CharField(max_length=32)),
                ('code', models.CharField(choices=[('irt', 'Irt'), ('aban', 'Aban')], max_length=10, unique=True)),
                ('price', utilities.fields.decimal.CurrencyDecimalField(decimal_places=7, default=Decimal('4'), max_digits=22)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان به روزرسانی')),
                ('amount', utilities.fields.decimal.CurrencyDecimalField(decimal_places=7, max_digits=22)),
                ('price', utilities.fields.decimal.CurrencyDecimalField(decimal_places=7, max_digits=22)),
                ('total_price', utilities.fields.decimal.CurrencyDecimalField(decimal_places=7, max_digits=22)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Init'), (1, 'Succeed'), (2, 'Wait For Partial')], default=0)),
                ('is_partial', models.BooleanField()),
                ('start_buying', models.DateTimeField(blank=True, null=True)),
                ('pending_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
